### PR TITLE
Architecture/restructure

### PR DESCRIPTION
**Pull request by ricexen**

### CODE REVIEW

**Comment by xentyo** [comment]
This it's just a suggestion but it can a social network visualizer or even a tool to know how you can relate with other people as a suggestion, like a way to get along with that certain individual.

**Comment by CiKu370** [comment]
Tx to @ricexen to recreate this project. I am very grateful to you.

**Comment by CiKu370** [comment]
but I will replace the logo with the old logo and some other functions I might also replace. hope you do not mind

**Comment by 0xlousie** [comment]
Please accept my apologies in advance. after I checked the changes you made this were very different from what I imagined. I will review with my friend later and I will promote your OSIF remake to my social media account.

**Comment by ricexen** [comment]
> but I will replace the logo with the old logo and some other functions I might also replace. hope you do not mind

Be free to change what you consider to change, I changed to show that the anteater know searches walking.

**Pull request merged**
